# https://book.getfoundry.sh/reference/config/overview

[profile.default]

libs = ["lib"]

optimizer = true
optimizer_runs = 1

remappings = [
	"@ens/=lib/ens-contracts/contracts/",
	"@oz/=lib/openzeppelin-contracts/contracts/",
	"lib/ens-contracts/:@openzeppelin/contracts-v5=lib/openzeppelin-contracts/contracts/" # for UniversalResolver.sol
]

# forge i foundry-rs/forge-std
# forge i ensdomains/ens-contracts@staging
# forge i OpenZeppelin/openzeppelin-contracts@release-v5.3
